### ISSUE TITLE
Session Time Out dan Logout

### ISSUE THREAD

**Issue by Widiyanto** [endymuhardin/belajar-spring-multiauth#1]
Izin bertanya Pak untuk settingan `session time out`, 
saya sudah menambahkan settingan di `server.servlet.session.timeout=1m` di `application.properties`, dan 

`@Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .antMatchers("/login**").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                	.loginPage("/login")
                	.failureHandler(fhandler)
                	.permitAll()
                .and()
                .logout()
                	.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
                	.deleteCookies("JSESSIONID")
                	.logoutSuccessHandler(customLogoutSuccessHandler)
            	.and()
            		.sessionManagement()
            		.maximumSessions(1)
            		.maxSessionsPreventsLogin(true)
            		.sessionRegistry(sessionRegistry);
    }`

saya batasi 1 session untuk tiap user.

1. saya login pada aplikasi.
2. saya logout dengan klik button logout.
3. saya login kembali dan berhasil login.
4. saya tunggu sampai session habis sendiri.
5. ketika saya login kembali, saya tidak bisa masuk aplikasi karena mendapatkan exception `Maximum sessions of 1 for this principal exceeded`.

pertanyaanya kalo session habis tidak otomatis logout ya Pak?

**Comment by endymuhardin** [comment]
Pesan error
Maximum sessions of 1 for this principal exceeded.

itu disebabkan karena konfigurasinya melarang satu user login lebih dari
satu kali.
.sessionManagement() .maximumSessions(1)

Ada dua pilihan pembatasan concurrent login:
1. Yang duluan masuk menang
2. Yang belakangan masuk mengusir yang duluan.

Kamu pakai opsi pertama. Makanya keluar error seperti itu.
.maxSessionsPreventsLogin(true)

Session expire otomatis dianggap logout. Kalo tidak berhasil mungkin salah
cara mengetesnya.
Coba dites lagi dengan dua browser atau incognito windows.
Baca2 juga tutorial di sini
https://www.baeldung.com/spring-security-session

Endy Muhardin
http://software.endy.muhardin.com

**Comment by Widiyanto** [comment]
Sudah Pak ternyata harus meregisterkan code ini
`@Bean
    public HttpSessionEventPublisher httpSessionEventPublisher() {
        return new HttpSessionEventPublisher();
    }`
